spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: homework1
      username: admin
      password: admin
      authentication-database: admin

logging:
  level:
    org.springframework.data.mongodb.core: INFO

taskName: task2
